version: "3"

services:
  mc:
    image: minecraft-server-with-mods:latest
    build: .
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.19"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data
      - ./example:/root/.config/ferium
